### ISSUE TITLE
unreasonable memory usage when loading 7.6 spr/dat

### ISSUE THREAD

**Issue by divinity76** [dtroitskiy/NewEditor#2]
when loading tibia 7.6 .spr / .dat , using an x86 debug build with msvc2013, 
in 
https://github.com/dtroitskiy/NewEditor/blob/bac7df7c987d9b5c21bda97b77c450a3666d149e/src/DatSprReaderWriter.cpp#L214 / 
```c++
object->spriteIDs = unique_ptr <unsigned int[]> (new unsigned int[object->spriteCount]);
```
it tries to allocate 4294967295 bytes, or 4.2GB , of memory, which is unreasonable for a 32bit x86 build, and this happens: http://prntscr.com/60u6qt 

if 32bit x86 is supposed to be supported, i suggest finding a way to reduce memory usage here ;)

(im for unknown reasons unable to link wxmsw30u_core.lib , aka the non-debug version, using msvc2013, but i can link wxmsw30ud_core.lib , aka the debug version, thus i am unable to test a non-debug build at this time :o )

**Comment by dtroitskiy** [comment]
I probably need to describe that in README.md (still I believe this is described in help), but at the moment editor is supposed to load only 9.60 format and it uses it as well for saving files. Thus I guess it reads sprite count incorrectly and tries to allocate that much memory.
I was thinking about adding signature check, but for some reason haven't added it yet. For now I don't plan to add support for other versions, but you are free to fork and add it yourself, that shouldn't be tough task, I believe.

**Comment by dtroitskiy** [comment]
Probably I'll deploy binary version it time, when editor will be more finished, but for now you can download latest win32 release version here - https://dl.dropboxusercontent.com/u/10046421/NewEditor.zip

**Comment by divinity76** [comment]
oh ok, that explains it. well for the time being, ill be using Black Demon's .dat/.spr editor for 7.6 :p
